### ISSUE TITLE
Revert deletion of code segments

### ISSUE THREAD

**Issue by timmens** [OpenSourceEconomics/econ-project-templates#101]
To make the GitHub actions run in PR #99 I had to remove functionality. Perspectively, this needs to be reverted.

- [ ] (1) Add interrogate hook to the inner project
- [ ] (2) Add mypy hook to the inner project
- [x] Add the ``make html`` test for inner project
   The inner documentation was removed so this is obsolete.

### (1) Add interrogate hook to the inner project

This issue can easily be resolved by adding
```yaml
-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0  # or master if you're bold
    hooks:
      - id: interrogate
        exclude: ^tests
        args: [--config=pyproject.toml
```
to ``.pre-commit-config.yaml`` in the inner project, and
```toml
[tool.interrogate]
ignore-init-method = true
ignore-init-module = true
ignore-module = true
ignore-nested-functions = true
ignore-nested-classes = true
ignore-setters = false
fail-under = 95
exclude = ["tests"]
ignore-regex = ["^task_.*"]
verbose = 2
quiet = false
color = true
```
to the ``pyproject.toml``.

### (2) Add mypy hook to the inner project

Decide whether we want to use mypy in the inner project. If we drop mypy then the configuration in ``pyproject.toml`` needs to be deleted.
