### ISSUE TITLE
pytask-latex paths are not set correctly

### ISSUE THREAD

**Issue by janosg** [OpenSourceEconomics/econ-project-templates#133]
I had multiple bug reports from students that latex documents are not re-built after included figures or documents change. It seems that this comes from a wrong path in `pyproject.toml` that maybe was not updated after the `paper` folder was moved out of the `src` folder. 

The current entry in `pyproject.toml` look like this:

```toml
[tool.pytask.ini_options]
paths = ["./src/project_name", "./src/paper"]
```

I think it should look like this:

```toml
[tool.pytask.ini_options]
paths = ["./src/project_name", "./paper"]
```
