### ISSUE TITLE
GitHub Actions file has leftovers from gettsim

### ISSUE THREAD

**Issue by janosg** [OpenSourceEconomics/econ-project-templates#134]
This is as snippet from `main.yml`:

```yaml
    steps:
      - uses: actions/checkout@v3
      - name: create build environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          environment-name: "{{ cookiecutter.project_slug }}"
          cache-env: true
          extra-specs: |
            python=${{ matrix.python-version }}
      - name: run pytest
        shell: bash -l {0}
        run: |
          micromamba activate gettsim
          pytest --cov-report=xml --cov=./ --ignore=dashboard/
      - name: Upload coverage report.
        if: runner.os == 'Linux' && matrix.python-version == '3.11'
        uses: codecov/codecov-action@v3
```

It has at least 3 problems:

1. Once the `cookiecutter.project_slug` was not replaced
2. I tries to activate `gettsim`
3. The `--ignore=dashboard/` is probably a leftover from gettsim
