### ISSUE TITLE
BUG: codespell hook fails to ignore inst/WORDLIST

### ISSUE THREAD

**Issue by buddejul** [OpenSourceEconomics/econ-project-templates#173]
Tiny thing I just stumbled across:

The codespell hook seems to fail to ignore `inst/WORDLIST` hence pre-commits fail using the template defaults. 
That is despite the `pyproject.toml` setting
```toml
[tool.codespell]
skip = "*.ipynb,inst/WORDLIST"
```

A fix that worked for me was specifying it in `.pre-commit-config.yaml`, e.g. like so
```yaml
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        exclude: pixi\.lock|inst/WORDLIST
```

To reproduce:

- clone the repo
- `pixi install`
- `pre-commit install`
- `pre-commit run --all-files`

System: Windows-11-10.0.26100-SP0
